### ISSUE TITLE
Anmerkungen zu DocumentReference

### ISSUE THREAD

**Issue by mosaic-hgw** [hl7germany/einwilligungsmanagement#11]
Subject.Reference ist im Beispiel optional. alternativ seien auch Identfier möglich

Per definition des profils ist es aber subject.refrence pflicht
->entweder beispiel oder definition anpassen (lieber definition anpassen)

Subject.Identifier ist per Definition nur n=1 zulässig. Wir haben im Regelfall n (Fallr, PatId, SapId, studyPsn...)
->Bitte definition auf n=* anpassen, wenn möglich :)

Oder entsteht die Begrenzung durch Subject selbst? wäre dann subject von 1..1 auf 1..n ändernbar?

**Comment by lhitc** [comment]
Es wäre zumindest offener, nicht explizit das Vorhandensein einer Patient-Ressource zu erzwingen (somit also subject.reference von 1..1 auf 0..1 zu ändern).

Die Kardinalität von subject.identifier ist allerdings per Reference-Datentyp auf max. 1 begrenzt.
Gleiches gilt für DocumentReference.subject.
Eine Erweiterung von eingeschränkter Kardinalität ist in FHIR nicht erlaubt.
Insgesamt ist dies allerdings sinnvoll, da die Reference (ob nun literal oder logisch) ja nur auf das entsprechende Ziel verweisen soll.
Wenn ein Patient also mehrere Identifikatoren hat, sollten diese in der Patient-Ressource liegen (Patient.identifier 1...* im aktuellen Patient-Profil).
Insofern wäre dann aber auch die Verwendung von subject.reference wieder nötig, um auf diese Patient-Ressource zu verweisen - also erscheint der aktuelle Stand der Spezifikation mir genau passend für das beschriebene Problem.

Ggf. nochmal bei der nächsten Telko diskutieren?

Ergänzender Hinweis: sollten hier Änderungen vorgenommen werden, betrifft dies analog auch weitere Profile mit Patienten-Referenz.

**Comment by lhitc** [comment]
Diskussion MB/SL: Kann bleiben, wie es ist.
