### ISSUE TITLE
MII KDS: example-ConsentManagement-Patient.xml passt noch nicht mit MII KDS Patient Beispiel zusammen

### ISSUE THREAD

**Issue by SebStaeubert** [hl7germany/einwilligungsmanagement#12]
@lhitc Das ist eine Aufgabe im MII-Kontext und evtl. etwas für die nächste Telko.

Unser Beispiel hier passt nicht so recht zum [Minimal-Patienten](https://github.com/medizininformatik-initiative/kerndatensatzmodul-person/blob/master/beispiele/Example-Patient-Minimal.json) des Basismoduls Person im MII Kerndatensatz. Das Pseudonym für den Patienten ist dort zudem in der ResearchSubject Ressource, siehe [Beispiel MII KDS Patient Research Subject](https://github.com/medizininformatik-initiative/kerndatensatzmodul-person/blob/master/beispiele/Example-ResearchSubject.json). 

Man könnte nun denken, dass in der Consent Ressource man entweder eine Patient oder besser eine Ressource Subject Ressource referenzieren können sollte. Die [Argumentation im Zulip](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Being.20RESTFul.20in.20clinical.20research/near/153964711) spricht aber dagegen. Für das Studien-Setting bzw. den Einsatz der Consent Ressource in einem Forschungsvorhaben, würde das bedeuten, dass es mehrere Patient Ressourcen zu ein und dem selben Patienten geben muss - eine im Versorgungskontext mit IDAT und pseudonymisierte je Studie / Consent. Über eine Person Ressource könnten diese dann zusammengehalten werden, richtig? Ist die Person Ressource generell für das Record Linkage gedacht (quasi eine Art MPI in FHIR)?

**Comment by mosaic-hgw** [comment]
bitte schaut euch mal HAPI FHIR MDM an. off topic
https://hapifhir.io/hapi-fhir/docs/server_jpa_mdm/mdm.html

**Comment by lhitc** [comment]
AG Einw. 2021-03-18:

MII-spezifische Beispiele ggf. dort einbringen / erstellen.

Fragen wurden besprochen und geklärt.
