### ISSUE TITLE
Beispiel ResearchStudy validiert noch nicht vollständig

### ISSUE THREAD

**Issue by mosaic-hgw** [hl7germany/einwilligungsmanagement#15]
https://simplifier.net/einwilligungsmanagement/researchstudy-example-duplicate-2/$validate

NotSupported             : Terminology service failed while  validating code 'image/png' (system ''): Cannot resolve canonical  reference 'urn:ietf:bcp:13' to CodeSystem                               ResearchStudy.extension[1].valueAttachment[0].contentType[0] | 6004 |  
-- | -- | --
  |   | Incomplete             : Unable to resolve reference to profile 'http://ths-greifswald.de/fhir/gics/domain/properties/SCANS_SIZE_LIMIT'                               ResearchStudy.extension[3]

Ist es ok, das SCAN_SIZE_LIMIT drin zu lassen? Alternativ raus und es kommt dann in spätere gics extensions rein

**Comment by lhitc** [comment]
Das CodeSystem für die MIME Types (urn:ietf:bcp:13) ist auf Simplifier nicht hinterlegt. Diese Warnung taucht an verschiedenen Stellen auf und muss hier ignoriert werden.

Die unbekannte Extension ist ja ein Beispiel, wie man beliebige eigene Extensions anhängt.
Um den Error raus zu bekommen, müssen wir die entweder entfernen oder hinnehmen und ggf. darauf hinweisen.

**Comment by lhitc** [comment]
Diskussion MB/SL: Zusatz-Extension hier entfernen, um im Rahmen des IG konsistent zu bleiben.
