### ISSUE TITLE
Beispiel TemplateFrame validiert noch nicht

### ISSUE THREAD

**Issue by mosaic-hgw** [hl7germany/einwilligungsmanagement#16]
https://simplifier.net/einwilligungsmanagement/b191dd03-bbb9-45da-ab5f-c811bc27e9a3/$validate

1. Beispiel validiert noch nicht
2. Kommentar führt zu Verwirrung, da es Eindruck macht, dass es sich um QuestionnaireComposed handelt

**Comment by lhitc** [comment]
erledigt
