### ISSUE TITLE
Bitte  erweitern ContextIdentifierType

### ISSUE THREAD

**Issue by mosaic-hgw** [hl7germany/einwilligungsmanagement#17]
// PI Patient internal identifier ->Patienten Id
// PT Patient external identifier ->z.B. SAP ID
// VN Visit number ->gemäß Beschreibung für Fallnummern 

alle http://hl7.org/fhir/v2/0203

oder ist eine erweiterung nicht erforderlich, da valueset "offen"?

**Comment by lhitc** [comment]
PI und PT wären sicher sinnvoll, wahrscheinlich auch noch einige andere aus 0203.

Visit Number ist allerdings kein Identifikator für Patienten, sondern einer für Encounter.

Ursprünglich wollten wir hier nur unsere "Spezial-Typen" abbilden und alles andere für den Bedarfsfall erlauben, daher das extensible Binding.
Die Frage wäre, ob wir hier z.B. noch ein patienten-relevantes Subset aus http://fhir.de/ValueSet/identifier-type-de-basis aufnehmen - oder ob wir es lassen, wie es ist und nur textuell auf das Basis-DE-ValueSet hinweisen.
