### ISSUE TITLE
Finalisierung für Ballot-Release

### ISSUE THREAD

**Issue by lhitc** [hl7germany/einwilligungsmanagement#18]
- [x] in allen Ressourcen Version und Publishing Date einheitlich setzen
- [x] alle Ressourcen validieren
- [x] Paket erstellen

**Comment by SebStaeubert** [comment]
@lhitc Ich habe gestern den Hinweis seitens MII bekommen, dass bei der Erstellung des Pakets, darauf geachtet werden soll, dass FHIR Logical Module vorher zu exportieren, damit später ein Vergleich diesbzgl. gemacht werden kann. Ist das machbar?
Das ist wohl bei einer vorhergehenden Ballotierung vergessen worden und machte dann Schwierigkeiten. Für Details kannst du ggf. bei @alexzautke nachfragen.

**Comment by lhitc** [comment]
FHIR Logicals Models werden bei HL7-D Ballots nicht benötigt, allerdings ein relevanter Punkt für den MII-Consent. Dort bitte einbringen.

**Comment by lhitc** [comment]
Ballot-Form: STU
Version 1.0.0-RC1

**Comment by lhitc** [comment]
erledigt
