### ISSUE TITLE
Consent.source - QuestionnaireResponse verpflichtend?

### ISSUE THREAD

**Issue by mw-uke** [hl7germany/einwilligungsmanagement#20]
Für `Consent.source` ist aktuell mit einer Kardinalität von 1..1 eine `QuestionnaireResponse` vorgesehen. Dies hieße, dass man in FHIR keinen Consent abbilden kann, ohne den entsprechenden Fragebogen zu hinterlegen? Ist diese Einschränkung sinnvoll und notwendig?

**Comment by lhitc** [comment]
AG-Meeting 2021-03-18:

Diese und ggf. analoge Rückreferenzen generell auf 0..1 bzw. 0..* setzen.
Im IG erklären, dass man auch nur Teile der Kette Template* / QC / QR / Consent einsetzen kann.

**Comment by lhitc** [comment]
Kardinalität auf 0..1 erweitert in:
- Consent(ConsentManagementConsent).source
- Questionnaire(ConsentManagementQuestionnaireComposed).derivedFrom

Hinweis: QuestionnaireResponse.questionnaire wurde auf 1..1 belassen, um den Basis-Workflow Fragebogen blanko => ausgefüllt nicht zu verwischen.
