### ISSUE TITLE
Klassendiagramm in IG integrieren

### ISSUE THREAD

**Issue by lhitc** [hl7germany/einwilligungsmanagement#21]
Klassendiagramm von Sebastian Stäubert sollte im IG vorhanden sein.

**Comment by SebStaeubert** [comment]
Hier das Klassendiagramm (Screenshot)
![image](https://user-images.githubusercontent.com/11329281/111634284-a717ee00-87f6-11eb-87e1-42e5b7dbf2df.png)

**Comment by mosaic-hgw** [comment]
ist drin https://simplifier.net/guide/einwilligungsmanagement/igeinwilligungsmanagement
