### ISSUE TITLE
Defekter Link

### ISSUE THREAD

**Issue by lhitc** [hl7germany/einwilligungsmanagement#24]
Auf der IG-Startseite ist der Link "Interoperabilitätsforum des BVITG" defekt ("http://" fehlt).
Weiterhin sollte "des BVITG" heraus genommen werden, da das Interop-Forum eine breit unterstützte Plattform ist.

**Comment by SebStaeubert** [comment]
@lhitc Es gibt noch einen weiteren defekten Link in der Beschreibung der ['Domain Research Study'](https://simplifier.net/guide/Einwilligungsmanagement/ResearchStudy).

**Comment by lhitc** [comment]
erledigt
