### ISSUE TITLE
Consent.patient literale Referenz verpflichtend

### ISSUE THREAD

**Issue by julsas** [hl7germany/einwilligungsmanagement#25]
Consent.patient.reference ist 1..1 und erzwingt literale Referenz.
Vorschlag: wieder auf 0..1 ändern, um auch nur Verwendung logischer Referenzen zu ermöglichen.

**Comment by lhitc** [comment]
Sollte so nicht sein; wir haben ja im IG sogar explizit ein Beispiel für logische Referenzen.

Anpassung ist auch für DocumentReference und QuestionnaireResponse relevant.
