### ISSUE TITLE
Signaturtypen reviewen/ergänzen

### ISSUE THREAD

**Issue by lhitc** [hl7germany/einwilligungsmanagement#30]
AG-Meeting 10.03.2023:
Die Signaturtypen (in Provenance und QuestionnaireComponsed Extension questionnaire-signatureRequired) sollten nochmals auf möglich benötigte Werte geprüft werden sowie eine eindeutige Beudeutung im Kontext des Leitfadens erhalten.

=> ValueSet https://www.hl7.org/fhir/R4/valueset-signature-type.html auf Rrelevanz durchgehen und Bedeutung festlegen

Cave: aktuell ist das komplette VS gebunden, d.h. alle Codes sind möglich.
Das Binding ist extensible, d.h. weitere Bedeutungen sind individuell in den einzelnen Implementierung ebenfalls möglich(!)

Es sollte aber mindestens für die von unserer AG erkannten Signaturtypen eine ein-eindeutige Bedeutung definiert werden (NICHT Übersetzung!)

**Comment by mosaic-hgw** [comment]
Vorschlag

**Gesetzlicher Vertreter z.b. Eltern bei Kindeseinwilligung** (0-n)

1.2.840.10065.1.12.1.11 	**Consent Witness Signature**	the signature of an individual who has witnessed the health care provider counselling a patient.

**Einwilligungspatient** (0-1)

1.2.840.10065.1.12.1.7 	**Consent Signature**	the signature of an individual consenting to what is described in a health information document.

**Aufklärende Person** (0-n)

1.2.840.10065.1.12.1.5 	**Verification Signature**	a signature verifying the information contained in a document. (Example a physician is required to countersign a verbal order that has previously been recorded in the medical record by a registered nurse who has carried out the verbal order.)

**Comment by SebStaeubert** [comment]
Zustimmung aus der TF Consent Umsetzung.
