### ISSUE TITLE
Hinweis zum Systemverhalten bei Widerrufen ergänzen

### ISSUE THREAD

**Issue by lhitc** [hl7germany/einwilligungsmanagement#31]
AG-Meeting 10.03.2023:
Im IG sollte darauf hingewiesen werden, dass die Semantik von Widerrufen korrekt auf die Consent-Provisions umgesetzt werden muss.

Beispiel:
"ja (ich stimme zu)" versus "ja (ich widerrufe)"

**Comment by mosaic-hgw** [comment]
Vorschlag

Im Fall von Widerrufen muss sichergestellt werden, dass semantische Bedeutung vom ausgefüllten Dokument bis hin zur maschinenlesbaren Interpretation korrekt in der Consent-Ressource abgebildet wird (z.B. im Fall von Widerrufe, Widersprüchen und Ablehnung)

**Comment by mosaic-hgw** [comment]
![grafik](https://user-images.githubusercontent.com/22166209/224272906-b4dc7fbc-4be6-4a13-9cfb-0b6071910516.png)
