### ISSUE TITLE
Valueset erweitern: TemplateType

### ISSUE THREAD

**Issue by mosaic-hgw** [hl7germany/einwilligungsmanagement#35]
Valueset um  "Einwilligung (Typ: Opt-Out) erweitern

**Comment by lhitc** [comment]
Neuer Code: CONSENT-OPT-OUT ; Definition/Hinweis: Fokus liegt auf maschineller Nutzung. Text analog Hinweis auf https://simplifier.net/guide/Einwilligungsmanagement/QuestionnaireResponse?version=current
Außerdem Erläuterung ergänzen zu (Opt-In-)Einwilligung im CS (IG-Page)
