### ISSUE TITLE
Aktualisierung Consent-Profil im IG: Kardinalität source anpassen

### ISSUE THREAD

**Issue by mosaic-hgw** [hl7germany/einwilligungsmanagement#38]
Kardinalität anpassen 0..* um optout consent (keine source) und auch einwilligungsstände (n dokumente zu ermöglichen

**Comment by lhitc** [comment]
Ziel ist, auch die QuestionnaireResponses zu referenzieren, die z.B. zum Consent-Typ "Einwilligungsstand" geführt haben.
=> Provenance.entity.what auf Q.Resp. erweitern.
