### ISSUE TITLE
Neues Codesystem/Valueset erzeugen um OptIn/OptOut Verhalten einer Einwilligungsdomain zu definieren

### ISSUE THREAD

**Issue by mosaic-hgw** [hl7germany/einwilligungsmanagement#39]
Codesystem/Valueset erzeugen und in ResearchStudy.category verwenden und ggf. Organization analog anpassen

Ziel: Default-Verhalten der Domain für root.provision festhalten
Bei OptIn ->DENY
Bei OptOut ->PERMIT

Dann in Consent.extension:domainReference.extension:domain verwendetbar machen

**Comment by lhitc** [comment]
Eigenes CS/VS wird nicht benötigt, da wir einfach http://hl7.org/fhir/ValueSet/consent-provision-type benutzen können.

zur Bindung an ResearchStudy und Organization wird eine Extension definiert.
