### ISSUE TITLE
Aktualisierung Consent-Profil im IG: Beispiel Consent mit Provisions zur Übermittlung eines Einwilligungsstandes

### ISSUE THREAD

**Issue by mosaic-hgw** [hl7germany/einwilligungsmanagement#40]
Beispiel erzeugen und im IG einbinden

inhaltliche Rücksprache mit @mosaic-hgw

**Comment by lhitc** [comment]
templateType ergibt m.E. im Kontext Einwilligungsstand keinen Sinn, daher nicht ins Beispiel aufgenommen.

Sollte die Verwendung der category-Slices evtl. näher im IG erläutert werden?

**Comment by lhitc** [comment]
AG-Meeting 19.01.2024:

- [ ] Neue Spalte "Template Type" in Tabelle auf Consent-Page ergänzen (ja/nein Info)
- [ ] Multiple Policies entfallen i.d.R. (für MII z.B. generiersche OID ...184 statt versionsspezizifischer/Dokumentspezifischer OIDS)

**Comment by lhitc** [comment]
erledigt
