### ISSUE TITLE
Glossar um PCF und Co erweitern bzw aktualisieren

### ISSUE THREAD

**Issue by mosaic-hgw** [hl7germany/einwilligungsmanagement#45]
bestehenden Glossar um neue Entwicklungen und Begrifflichkeiten mit Blick auf PCF, ePA und Co erweitern bzw aktualisieren

https://simplifier.net/guide/Einwilligungsmanagement/GlossarundDatenmodell?version=current

**Comment by lhitc** [comment]
Zur Diskussion im AG-Meeting: Ist die Glossar-Grafik noch erforderlich (Darstellung des historischen Standes, jetzt liegt aber der Standard bereits vor)?

**Comment by lhitc** [comment]
AG-Meeting 30.04.2024: Grafik soll drin bleiben.

**Comment by mosaic-hgw** [comment]
- [ ] Excel Export Glossar Tabelle an AM @mbialke 
- [ ] Aktualisierung / Ergänzung Begriffe PCF @angela
- [ ] Begriffe in altem Bild ergänzen (einsortieren) @mbialke 
- [ ] 3LGM Version des Bildes @SebStaeubert

**Comment by mbialke** [comment]
- [ ] Begriffe PCF SER im Glossar eingangs erklären
