### ISSUE TITLE
Beispiel Ausleitung Consent-Module als Consent-Ressource ergänzen

### ISSUE THREAD

**Issue by mosaic-hgw** [hl7germany/einwilligungsmanagement#46]
Es muss klar werden: immer level2 provisions nutzen um policies darzustellen

Beispiel in Rücksprache mit @mosaic-hgw für IG Consent-Profil erzeugen
Fokus: unterschiedliche Gültigkeitszeiträume (z.b. mdat_erheben) ist essentiell.

Beispiel Grundlage MII BC Modul 1 mit mdat_erheben period.end nach 5Jahren

**Comment by lhitc** [comment]
erledigt
