### ISSUE TITLE
Beispiele aktualisieren und erweitern

### ISSUE THREAD

**Issue by lhitc** [hl7germany/einwilligungsmanagement#50]
- [x] Consent-Beispiele aktualisieren auf aktuelle Spec. des Profils (Beispiel 1+2)
- [x] Beispiele neu: Consent mit Provision zur Übermittlung eines Einwilligungsstandes ( vgl. #40 )
- [x] Beispiele neu: Consent mit Provision zur Abbildung eines Widerrufdokuments (vgl. #41 )
- [x] Beispiele neu: Consent mit Opt-Out Einwilligung
- [x] Beispiele neu: Consent mit Opt-Out Widerspruch
- [ ] Request-Beispiel: Suche nach Einwilligung einer bestimmten (Forschungs-)Domäne

**Comment by ths-community** [comment]
@lhitc sehr schön. optout einwilligungsbeispiel sieht gut aus. danke  :)

**Comment by lhitc** [comment]
erledigt

**Comment by SebStaeubert** [comment]
https://github.com/hl7germany/einwilligungsmanagement/blob/master/examples/example-ConsentManagement-Consent7.xml

Enthält ein "deny" in provision level 1 und weitere "deny"s in provision level 2 - macht das Sinn?
