### ISSUE TITLE
Klassendiagramm überarbeiten

### ISSUE THREAD

**Issue by lhitc** [hl7germany/einwilligungsmanagement#52]
- [x] Consent.sourceReference: 0..1 statt 1..1
- [x] Provenance.entity kann mehrfach vorkommen, um z.B. die multiplen Quellen eines Einwilligungstand-Consents zu referenzieren -> ist gegeben, da Provenance.entity 0..*
  - [x] Referenzierung auf QuestionnaireResponse  -> bereits vorhanden (target)
  - [x] Referenzierung auf Consent ermöglichen -> eingefügt (target)

Frage(n):
- [x] Kardinalitäten analog zum [MII UML Diagramm](https://www.medizininformatik-initiative.de/Kerndatensatz/Modul_Consent/IGMIIKDSModulConsent-AnwendungsflleInformationsmodell-UML.html)?

- [x] Grafik in Englisch
- [x] Layout überarbeiten

**Comment by SebStaeubert** [comment]
@lhitc [aktualisierte Grafik](https://github.com/hl7germany/einwilligungsmanagement/blob/master/figures/UML-Diagramm_HL7-IG.png) bitte [in IG übernehmen](https://simplifier.net/guide/Einwilligungsmanagement/Profiles?version=current).

**Comment by lhitc** [comment]
- [ ] Das Diagramm enthält eine MII-Referenz(?) => klären

**Comment by mosaic-hgw** [comment]
- [ ] ag ewm bild hat keine kardinalitäten, einmal mit mii bild abgleichen. wenn sich kardinalitäten und Spezi nicht beißen, dann gern in Bild aufnehmen @SebStaeubert
