### ISSUE TITLE
Provenance.entity.what erweitern

### ISSUE THREAD

**Issue by lhitc** [hl7germany/einwilligungsmanagement#53]
Im Provenance-Profil noch das targetProfile Consent ergänzen.
Zusammenhänge (target === Consent, entity[role=source] := Quellen, ja nachdem können das Consents oder (/und?) QuestionnaireResponses sein.

- [x] Profil erweitern
- [x] Beispiel-Provenance mit Verweis auf Consent (Einwilligungsstand) und drei Questionnaires erstellen

**Comment by ths-community** [comment]
- [ ] und bitte danach Spalte Kardinalität in Tabelle 3 auf ConsentProfilseite anpassen
