### ISSUE TITLE
Ergänzung von Suchparametern und Beispielen für Consent-Abfragen unter Berücksichtigung ResultType

### ISSUE THREAD

**Issue by ths-community** [hl7germany/einwilligungsmanagement#58]
Wir berücksichtigen in unseren Consent-Beschreibungen einheitlich bereits ResultType.

Wir sollten, um den IG abzurunden, auch einen Suchparamter für Consent passend dazu definieren, um die Art der Ausleitung von Consent-Ressourcen per Abfrage vorgeben zu können.

z.B. zur Ausleitung von Consent-Resourcen je ausgefülltem Einwilligungsdokument
{{baseUrl}}/Consent?category=http://fhir.de/ConsentManagement/CodeSystem/ResultType|document

z.B. zur Ermittlung von Einwilligungsständen bezogen auf eine konkrete Personenkennung eines bestimmten Forschungsprojektes
{{baseUrl}}/Consent?category=http://fhir.de/ConsentManagement/CodeSystem/ResultType|consent-status&domain:identifier=myProject&domain:identifier=myProject&patient.identifier=XYZ

**Comment by mosaic-hgw** [comment]
@lhitc bitte umsetzen
- [ ] resulttype durchaus sinnvoll, aber andere slices dann ebenfalls unterstützen
- [ ] category+person ebenfalls sinnvoll

**Comment by lhitc** [comment]
done
