### ISSUE TITLE
Klärung Art der Einwilligung oder Art der Einwilligungsvorlage

### ISSUE THREAD

**Issue by mosaic-hgw** [hl7germany/einwilligungsmanagement#6]
Im TemplateFram wird die Art der Einwilligungsvorlage per Code definiert mit CodeySystem https://simplifier.net/guide/Einwilligungsmanagement/TemplateType2

Im Consent wird die Art der Einwilligung durch ConsentCategoryCodes definiert https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/81415

Aktuell wird im QuestionnaireComposed, der ja nur eine Print/Render-vErsion des TemplateFrame ist, im Beispiel die Art der Einwilliungsvorlage per LOINC Code definiert.

Hier wäre es doch besser ebenfalls das CodeSystem TemplateType zu nutzen oder statt des LOINC Codes, der ja eher auf einen ConsentCategoryCodes  abzielt? Oder?

Bitte um Klärung

**Comment by lhitc** [comment]
Ist hier nicht erforderlich. Consent.category wird im Regelfall = "59284-0" sein (ggf. natürlich in abgeleiteten Spezifikationen auch anders).
Das VS ist extensible gebunden, somit kein Problem.
