### ISSUE TITLE
Im IG die Mechanismen von Consent.provision erläutern

### ISSUE THREAD

**Issue by lhitc** [hl7germany/einwilligungsmanagement#7]
Im IG die Mechanismen von Consent.provision erläutern:
- Nutzbarkeit als Hierarchie
- Bedeutung von period, dataPeriod, code, action, ...
- policy|policyRule vs./in Kombination mit provision

**Comment by lhitc** [comment]
Auch erläutern: Vor- und Nachteile von n Consent mit einfachen Provisions vs. 1 Consent mit verschachtelten Provisions

**Comment by mosaic-hgw** [comment]
- [x] Nutzbarkeit
- [x]  verschachtelte provisions
- [x] gesamtconsent oder einzel consent

für den rest brauche ich mehr infos. @lhitc 
-  Bedeutung von period, dataPeriod, code, action, ...
- policy|policyRule vs./in Kombination mit provision

**Comment by mosaic-hgw** [comment]
erledigt.
